version: '2'
services:
    mongo-1-2:
        container_name: "mongo-1-2"
        image: mongo
        ports:
            - "30012:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: mongo
        ports:
            - "30013:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        restart: always

    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        restart: always



