version: '2'
services:
  api:
    command: pm2-docker --watch server/server.js
    image: gjscut/water_watcher_api_server
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: development
      NODE_ENV: development
      NODE_CONFIG_DIR: ./config
      NODE_APP_INSTANCE: ''
    links:
      - mongo:mongodb
      - redis:redis
    ports:
      - "3000:3000"
      - "443:3001"
    volumes:
      - .:/docker-node-express-boilerplate

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - /path/to/redis-persistence:/bitnami/redis
    restart: always

  mongo:
   image: mongo
   ports:
     - "27017:27017"
   restart: always 

  lb:
    image: gjscut/loadbalance
    build: config/consule
    links:
      - api
    ports:
      - "88:80"

  consul:
    image: gliderlabs/consul-server:latest
    command: -bootstrap
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  registrator:
    image: gliderlabs/registrator:master
    links:
      - consul
    command: -internal -resync 600 consul://consul:8500
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

