version: '2'
services:
    mongo-2-2:
        container_name: "mongo-2-2"
        image: mongo
        ports:
            - "30022:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017
        restart: always

    mongo-2-3:
        container_name: "mongo-2-3"
        image: mongo
        ports:
            - "30023:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017
        restart: always

    mongo-2-1:
        container_name: "mongo-2-1"
        image: mongo
        ports:
            - "30021:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017
        links:
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        restart: always



