version: '3'
services:
  api:
    build: .
    command: pm2-docker --watch server/server.js
    image: dockernodeexpressboilerplate_api
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: development
      NODE_ENV: development
      NODE_CONFIG_DIR: ./config
      NODE_APP_INSTANCE: ''
    external_links:
      - mongo-router:mongodb
    ports:
      - "3000"
    volumes:
      - .:/docker-node-express-boilerplate

  lb:
    image: gjscut/loadbalance
    depends_on:
      - api
    ports:
      - "80:80"

  consul:
    image: gliderlabs/consul-server:latest
    command: -bootstrap
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  registrator:
    image: gliderlabs/registrator:master
    depends_on:
      - consul
    command: -internal -resync 600 consul://consul:8500
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

